# Generated by Django 4.2.10 on 2024-03-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawPriceData",
            fields=[
                ("open", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                ("low", models.FloatField(blank=True, null=True)),
                ("close", models.FloatField(blank=True, null=True)),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("dividends", models.FloatField(blank=True, null=True)),
                ("stock_splits", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("symbol", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "raw_price_data",},
        ),
    ]
