# Generated by Django 4.2.10 on 2024-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawpricedata",
            name="id",
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
    ]
