# Generated by Django 5.1.1 on 2024-10-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSpecificRisk',
            fields=[
                ('id', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('version_date', models.DateField(blank=True, max_length=12, null=True)),
                ('half_life', models.IntegerField(blank=True, null=True)),
                ('specific_risk', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_specific_risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exposures',
            fields=[
                ('market', models.IntegerField(blank=True, null=True)),
                ('reversal', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('new_coin', models.FloatField(blank=True, null=True)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('id', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('return_field', models.FloatField(blank=True, db_column='return', null=True)),
                ('transformed_market_cap', models.FloatField(blank=True, null=True)),
                ('core_universe', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exposures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactorReturns',
            fields=[
                ('market', models.IntegerField(blank=True, null=True)),
                ('reversal', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('new_coin', models.FloatField(blank=True, null=True)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('version_date', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'factor_returns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('return_field', models.FloatField(blank=True, db_column='return', null=True)),
                ('risk_free_rate', models.FloatField(blank=True, null=True)),
                ('total_return', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'returns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskFreeRates',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('risk_free_rate', models.FloatField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'risk_free_rates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RSquares',
            fields=[
                ('id', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('version_date', models.DateField(blank=True, max_length=12, null=True)),
                ('r2_core', models.FloatField(blank=True, null=True)),
                ('r2_adj', models.FloatField(blank=True, null=True)),
                ('nobs', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'r_squares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificReturns',
            fields=[
                ('id', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('specific_return', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specific_returns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TStatistics',
            fields=[
                ('market', models.IntegerField(blank=True, null=True)),
                ('reversal', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('new_coin', models.FloatField(blank=True, null=True)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('version_date', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 't_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vifs',
            fields=[
                ('market', models.IntegerField(blank=True, null=True)),
                ('reversal', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('new_coin', models.FloatField(blank=True, null=True)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('version_date', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'vifs',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rawpricedata',
            options={'managed': False},
        ),
    ]
