# Generated by Django 4.2.10 on 2024-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_calculator", "0002_rawpricedata_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreSpecificRisk",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("date", models.TextField(blank=True, null=True)),
                ("half_life", models.IntegerField(blank=True, null=True)),
                ("specific_risk", models.FloatField(blank=True, null=True)),
                ("version_date", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "core_specific_risk", "managed": False,},
        ),
        migrations.CreateModel(
            name="Exposures",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("ticker", models.TextField(blank=True, null=True)),
                (
                    "return_field",
                    models.FloatField(blank=True, db_column="return", null=True),
                ),
                ("core_universe", models.IntegerField(blank=True, null=True)),
                ("market", models.IntegerField(blank=True, null=True)),
                ("transformed_market_cap", models.FloatField(blank=True, null=True)),
                ("reversal", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("new_coin", models.FloatField(blank=True, null=True)),
                ("momentum", models.FloatField(blank=True, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
                ("date", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "exposures", "managed": False,},
        ),
        migrations.CreateModel(
            name="FactorReturns",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("market", models.FloatField(blank=True, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
                ("momentum", models.FloatField(blank=True, null=True)),
                ("reversal", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("new_coin", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("version_date", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "factor_returns", "managed": False,},
        ),
        migrations.CreateModel(
            name="Returns",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "return_field",
                    models.FloatField(blank=True, db_column="return", null=True),
                ),
                ("risk_free_rate", models.FloatField(blank=True, null=True)),
                ("total_return", models.FloatField(blank=True, null=True)),
                ("symbol", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "returns", "managed": False,},
        ),
        migrations.CreateModel(
            name="RiskFreeRates",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("risk_free_rate", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("symbol", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "risk_free_rates", "managed": False,},
        ),
        migrations.CreateModel(
            name="RSquares",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("r2_core", models.FloatField(blank=True, null=True)),
                ("r2_adj", models.FloatField(blank=True, null=True)),
                ("nobs", models.FloatField(blank=True, null=True)),
                ("version_date", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "r_squares", "managed": False,},
        ),
        migrations.CreateModel(
            name="SpecificReturns",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("ticker", models.TextField(blank=True, null=True)),
                ("specific_return", models.FloatField(blank=True, null=True)),
                ("date", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "specific_returns", "managed": False,},
        ),
        migrations.CreateModel(
            name="TStatistics",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("market", models.FloatField(blank=True, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
                ("momentum", models.FloatField(blank=True, null=True)),
                ("reversal", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("new_coin", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("version_date", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "t_statistics", "managed": False,},
        ),
        migrations.CreateModel(
            name="Vifs",
            fields=[
                ("id", models.AutoField(default=-1, primary_key=True, serialize=False)),
                ("market", models.FloatField(blank=True, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
                ("momentum", models.FloatField(blank=True, null=True)),
                ("reversal", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("new_coin", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("version_date", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "vifs", "managed": False,},
        ),
    ]
