# Generated by Django 5.1.1 on 2024-10-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_calculator', '0002_corespecificrisk_exposures_factorreturns_returns_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tstatistics',
            options={'managed': True},
        ),
    ]
