# Generated by Django 5.1.1 on 2024-10-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_calculator', '0003_alter_tstatistics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tstatistics',
            options={'managed': False},
        ),
    ]
