# Generated by Django 5.1.1 on 2024-10-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_calculator', '0004_alter_tstatistics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawpricedata',
            options={'managed': False},
        ),
    ]
